---

language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl git
 - git clone https://github.com/Stouts/Stouts.supervisor roles/Stouts.supervisor
 - git clone https://github.com/Stouts/Stouts.nginx roles/Stouts.nginx
 - git clone https://github.com/Stouts/Stouts.redis roles/Stouts.redis
 - git clone https://github.com/Stouts/Stouts.python roles/Stouts.python
install:
  - pip install ansible>=1.6.0
script:
  - echo localhost > inventory
  - ansible-playbook --syntax-check -i inventory test.yml
  - ansible-playbook -i inventory test.yml --connection=local --sudo
 
sentry_home: /home/travis/sentry
sentry_cache_backend: ""
sentry_broker_url: ""
sentry_buffer: ""
